# Generated by Django 2.2.5 on 2020-05-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('NomPays', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ISO', models.CharField(max_length=3)),
            ],
        ),
    ]
