# Generated by Django 2.2.5 on 2020-04-21 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('IdAvion', models.AutoField(primary_key=True, serialize=False)),
                ('Modele', models.CharField(max_length=200)),
                ('IATA', models.CharField(max_length=3)),
                ('OACI', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('NomPays', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ISO', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('NomVille', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('NomPays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monappli.Pays')),
            ],
        ),
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('NomCompagnie', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Alias', models.CharField(max_length=10)),
                ('IATA', models.CharField(max_length=2)),
                ('OACI', models.CharField(max_length=3)),
                ('NomPays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monappli.Pays')),
            ],
        ),
        migrations.CreateModel(
            name='Aeroport',
            fields=[
                ('IdAeroport', models.AutoField(primary_key=True, serialize=False)),
                ('NomAeroport', models.CharField(max_length=200)),
                ('IATA', models.CharField(max_length=3)),
                ('OACI', models.CharField(max_length=4)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Altitude', models.FloatField()),
                ('Ville', models.CharField(max_length=200)),
                ('NomPays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monappli.Pays')),
            ],
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('IdAccident', models.AutoField(primary_key=True, serialize=False)),
                ('Time', models.DateTimeField()),
                ('Nb_occupants', models.IntegerField()),
                ('Nb_deces', models.IntegerField()),
                ('Emplacement', models.CharField(max_length=200)),
                ('Phase_de_vol', models.CharField(max_length=200)),
                ('Nature', models.CharField(max_length=200)),
                ('Statut', models.CharField(max_length=200)),
                ('Degats', models.CharField(max_length=200)),
                ('IdAeroport_arrivee', models.ManyToManyField(related_name='arrivee', to='monappli.Aeroport')),
                ('IdAeroport_depart', models.ManyToManyField(related_name='depart', to='monappli.Aeroport')),
                ('IdAvion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monappli.Avion')),
                ('NomCompagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monappli.Compagnie')),
                ('NomPays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monappli.Pays')),
            ],
        ),
    ]
