# Generated by Django 2.2.5 on 2020-05-08 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id_avion', models.AutoField(primary_key=True, serialize=False)),
                ('modele', models.CharField(max_length=200, unique=True)),
                ('iata', models.CharField(default=float("nan"), max_length=3, null=True)),
                ('oaci', models.CharField(default=float("nan"), max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('nom_pays', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('iso', models.CharField(default=float("nan"), max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id_ville', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ville', models.CharField(max_length=200)),
                ('nom_pays', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monappli.Pays')),
            ],
        ),
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('nom_compagnie', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('alias', models.CharField(default=float("nan"), max_length=30, null=True)),
                ('iata', models.CharField(default=float("nan"), max_length=3, null=True)),
                ('oaci', models.CharField(default=float("nan"), max_length=3, null=True)),
                ('nom_pays', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monappli.Pays')),
            ],
        ),
        migrations.CreateModel(
            name='Aeroport',
            fields=[
                ('id_aeroport', models.AutoField(primary_key=True, serialize=False)),
                ('nom_aeroport', models.CharField(max_length=200, unique=True)),
                ('iata', models.CharField(default=float("nan"), max_length=3, null=True)),
                ('oaci', models.CharField(default=float("nan"), max_length=4, null=True)),
                ('latitude', models.FloatField(default=None, null=True)),
                ('longitude', models.FloatField(default=None, null=True)),
                ('altitude', models.FloatField(default=None, null=True)),
                ('ville', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monappli.Ville')),
            ],
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id_accident', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=None, null=True)),
                ('nb_occupants', models.IntegerField(default=None, null=True)),
                ('nb_deces', models.IntegerField(default=None, null=True)),
                ('emplacement', models.CharField(default=float("nan"), max_length=200, null=True)),
                ('phase_de_vol', models.CharField(default=float("nan"), max_length=200, null=True)),
                ('nature', models.CharField(default=float("nan"), max_length=200, null=True)),
                ('statut', models.CharField(default=float("nan"), max_length=200, null=True)),
                ('degats', models.CharField(default=float("nan"), max_length=200, null=True)),
                ('id_aeroport_arrivee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrivee', to='monappli.Aeroport')),
                ('id_aeroport_depart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depart', to='monappli.Aeroport')),
                ('id_avion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monappli.Avion')),
                ('nom_compagnie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monappli.Compagnie')),
                ('nom_pays', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monappli.Pays')),
            ],
        ),
    ]
