# Generated by Django 2.2.5 on 2020-04-21 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aeroport',
            name='NomPays',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='IdAeroport_arrivee',
        ),
        migrations.AddField(
            model_name='accident',
            name='IdAeroport_arrivee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='arrivee', to='monappli.Aeroport'),
        ),
        migrations.RemoveField(
            model_name='accident',
            name='IdAeroport_depart',
        ),
        migrations.AddField(
            model_name='accident',
            name='IdAeroport_depart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='depart', to='monappli.Aeroport'),
        ),
        migrations.AlterField(
            model_name='aeroport',
            name='Ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monappli.Ville'),
        ),
    ]
