# Generated by Django 2.2.5 on 2020-05-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('IdAvion', models.AutoField(primary_key=True, serialize=False)),
                ('Modele', models.CharField(max_length=200)),
                ('IATA', models.CharField(max_length=3)),
                ('OACI', models.CharField(max_length=4)),
            ],
        ),
    ]
