# Generated by Django 2.2.5 on 2020-04-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0002_auto_20200421_1135'),
    ]

    operations = [
    ]
