# Generated by Django 2.2.5 on 2020-05-06 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0002_avion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('NomCompagnie', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Alias', models.CharField(max_length=30)),
                ('IATA', models.CharField(max_length=3)),
                ('OACI', models.CharField(max_length=3)),
                ('NomPays', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monappli.Pays')),
            ],
        ),
    ]
