# Generated by Django 2.2.5 on 2020-04-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0003_auto_20200422_0751'),
    ]

    operations = [
    ]
