# Generated by Django 2.2.5 on 2020-05-06 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0003_compagnie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('NomVille', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('NomPays', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monappli.Pays')),
            ],
        ),
    ]
