# Generated by Django 2.2.5 on 2020-04-22 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0004_auto_20200422_0837'),
    ]

    operations = [
    ]
