# Generated by Django 2.2.5 on 2020-05-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0005_accident_aeroport'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeroport',
            name='Altitude',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='aeroport',
            name='Latitude',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='aeroport',
            name='Longitude',
            field=models.FloatField(default=None, null=True),
        ),
    ]
