# Generated by Django 2.2.5 on 2020-05-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0006_auto_20200506_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='Nb_occupants',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='accident',
            name='nb_deces',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
