# Generated by Django 2.2.5 on 2020-04-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0006_auto_20200422_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='Degats',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='accident',
            name='Emplacement',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='accident',
            name='Nature',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='accident',
            name='Phase_de_vol',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='accident',
            name='Statut',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='aeroport',
            name='IATA',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='aeroport',
            name='NomAeroport',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='aeroport',
            name='OACI',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='avion',
            name='IATA',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='avion',
            name='Modele',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='avion',
            name='OACI',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='compagnie',
            name='Alias',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='compagnie',
            name='IATA',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='compagnie',
            name='OACI',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='pays',
            name='ISO',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
