# Generated by Django 2.2.5 on 2020-04-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0007_auto_20200422_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pays',
            name='ISO',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
