# Generated by Django 2.2.5 on 2020-05-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0007_auto_20200506_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='Time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
