# Generated by Django 2.2.5 on 2020-04-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0008_auto_20200422_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='Nb_deces',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='Nb_occupants',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='Time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='aeroport',
            name='Altitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='aeroport',
            name='Latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='aeroport',
            name='Longitude',
            field=models.FloatField(blank=True),
        ),
    ]
