# Generated by Django 2.2.5 on 2020-04-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0009_auto_20200422_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compagnie',
            name='IATA',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
